services:
  asn1_codec:
    build:
      context: .
      dockerfile: Dockerfile.keeprunning
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_TYPE: "ON-PREM"
      ACM_CONFIG_FILE: adm.properties
      ACM_LOG_TO_CONSOLE: "${ACM_LOG_TO_CONSOLE}"
      ACM_LOG_TO_FILE: "${ACM_LOG_TO_FILE}"
      ACM_LOG_LEVEL: "${ACM_LOG_LEVEL}"
    restart: on-failure